# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a84712ca4c85f1f4bc54b9d9d18a51a535efb8ba7efa78a9874b09ec161d91ab6163e2c5cf0f0cb03a0f80fb0fb463c464c385005b281c35fd25016c108aeb6

test:
  secret_key_base: bd12291ec0581e937e44a268187e6743d1dd76cfbf9ec58577bfe85c11ca7523422efbc3f0f44ebe3fee54787f7277e3985a3bd27ceea0542e13c1973297e4ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
